Increase upgrade download timeout to 2 hours
elastic/elastic-agent pull request #1666
Opened 2022-11-01 10:20 UTC by joshdover

## What does this PR do?

Blocked by:
- [ ] https://github.com/elastic/elastic-agent/issues/1706

Increases the client-side timeout on downloading the agent upgrade binary to 120m. I've observed some machines on slow connections downloading as slow as 50Kb/s. Our largest artifact size is on linux, clocking in at around 370MB. My rough math shows that an agent downloading at this speed would take about 110 minutes to complete, so I chose 120 minutes as a new default value.

## Why is it important?

We want to improve the reliability of upgrades. Agents will soon retry their own upgrades start in 8.6 if they fail, but for agents on slow connections, they may never successfully complete with a 10 minute timeout. I can't think of a reason we need to have such a short timeout.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

2022-11-01 10:38 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-1666/detail/PR-1666/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-1666/detail/PR-1666/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-1666/detail/PR-1666/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-1666/detail/PR-1666/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://elastic-agent_1666.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2022-11-01T10:10:59.918Z&rangeTo=2022-11-01T10:30:59.918Z&transactionName=BUILD+elastic-agent%2Felastic-agent-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=71f7ee3734df9cd55b31a0dc3d278ce9&transactionId=0774bc8cdad38197)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-11-01T10:20:59.918+0000


* Duration: 17 min 18 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 5019  |
| Skipped      | 17 |
| Total        | 5036   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :green_heart: Flaky test report
Tests succeeded.



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages.


- `run integration tests` : Run the Elastic Agent Integration tests.


- `run end-to-end tests` : Generate the packages and run the E2E Tests.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-11-01 10:38 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 97.297% (`72/74`) | :+1: 
Files | 69.13% (`159/230`) | :+1: 
Classes | 69.231% (`315/455`) | :+1: 
Methods | 53.254% (`892/1675`) | :+1: 
Lines | 39.32% (`9638/24512`) | :-1: -0.012
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-11-01 13:42 UTC, aleksmaus commented
> Increases the client-side timeout on downloading the agent upgrade binary to 120s.
typo in the description? 120s == 120 seconds?
2 hours is a long time to be blocked on download in any code path.

2022-11-02 16:09 UTC, AndersonQ approved these changes

2022-11-02 19:05 UTC, michel-laterman approved these changes
lgtm.
However I think we should take the opportunity to highlight (in our docs) that the agent will not process any other actions when dealing with an update.

2022-11-02 19:11 UTC, cmacknz commented
> that the agent will not process any other actions when dealing with an update.

If this change is going to prevent the agent from handling other actions for up to 2 hours we shouldn't merge it as is. Increasing the timeout to 2 hours is valid given what Josh has observed in the field (potentially the timeout should be configurable), but the download needs to be made asynchronous if we are going to block other actions for that long.

2022-11-02 19:13 UTC, cmacknz requested changes
See the discussion above. We need the download step to be asynchronous if the timeout is going to be this long.

2022-11-03 09:46 UTC, joshdover commented
> However I think we should take the opportunity to highlight (in our docs) that the agent will not process any other actions when dealing with an update.

I noticed this as well shortly after posting this PR. The agent stops checking in while processing the upgrade action. Let's hold off on this until we discuss further.

2022-11-28 19:14 UTC, amitkanfer commented
@joshdover i see a couple of approvals here... what's the ETA for this?

2022-11-28 19:23 UTC, joshdover commented
This is blocked by https://github.com/elastic/elastic-agent/issues/1706. Without resolving that issue, the agent will be unable to accept any policy changes while it's downloading an upgrade artifact. A timeout of 2h is not acceptable in that case. We could consider still increasing it to something like 30m?

@nimarezainia Any thoughts?

2022-11-28 19:26 UTC, amitkanfer commented
> We could consider still increasing it to something like 30m

better than nothing.

2022-11-28 19:36 UTC, amitkanfer commented
thinking about it, maybe it's worth having 2 hours anyway... even if we're blocked on that other issue.
What's the difference if timeout will be from agent or from proxy... anyway download fails.

2023-01-30 15:45 UTC, jlind23 commented
Closing this as it is included in: https://github.com/elastic/elastic-agent/pull/2205

2023-01-30 15:45 UTC, closed without merging