no e2e if only docs
elastic/elastic-agent pull request #259
Opened 2022-03-28 12:14 UTC by narph

Adding condition for e2e tests to not run if there are only doc changes

## Why is it important?

e2e tests have failed after PR merge because of missing artifacts for docs only, the changes in Jenkins checks if changes are limited to docs and does not run the tests.

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

2022-03-28 12:52 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-259/detail/PR-259/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-259/detail/PR-259/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-259/detail/PR-259/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-259/detail/PR-259/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://elastic-agent_259.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2022-03-28T12:04:20.478Z&rangeTo=2022-03-28T12:24:20.478Z&transactionName=elastic-agent/elastic-agent-mbp/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=e506707eb12522a49d8ea8bd4f1f2640&transactionId=6fd5327b3819006f)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-03-28T12:14:20.478+0000


* Duration: 38 min 27 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages.


- `run integration tests` : Run the Elastic Agent Integration tests.


- `run end-to-end tests` : Generate the packages and run the E2E Tests.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-03-28 14:34 UTC, mdelapenya commented on .ci/Jenkinsfile
> +          expression { return isE2eEnabled() && env.ONLY_DOCS == "false"}
Adding @v1v as a reviewer for awareness

2022-03-28 14:34 UTC, mdelapenya approved these changes

2022-03-28 14:39 UTC, v1v requested changes
I don't think this is needed. See https://github.com/elastic/elastic-agent/blob/f042b82c8ce3da11ca9174be19a34b33fd724cc0/.ci/Jenkinsfile#L344-L349

The above condition is only if PRs

While https://github.com/elastic/elastic-agent/blob/f042b82c8ce3da11ca9174be19a34b33fd724cc0/.ci/Jenkinsfile#L238 is the one to run always on branches/tags


Maybe the docs validation should be done if the build is not PR based

2022-03-30 11:11 UTC, v1v commented on .ci/Jenkinsfile
> +          expression { return isE2eEnabled() && env.ONLY_DOCS == "false"}
```suggestion
          // package artefacts are not generated if ONLY_DOCS, therefore e2e should not run if ONLY_DOCS
          expression { return isE2eEnabled() && env.ONLY_DOCS == "false"}
```

2022-03-30 11:11 UTC, v1v approved these changes
Thanks Mariana for walking me through what's the issue about

2022-03-30 11:50 UTC, merged