Add changelog entry for Cloudbeat and the verifier
elastic/elastic-agent pull request #263
Opened 2022-03-29 20:40 UTC by ph

Missing changelog entry

2022-03-29 20:46 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-263/detail/PR-263/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-263/detail/PR-263/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-263/detail/PR-263/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-263/detail/PR-263/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://elastic-agent_263.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2022-03-29T20:30:33.890Z&rangeTo=2022-03-29T20:50:33.890Z&transactionName=elastic-agent/elastic-agent-mbp/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=f3c2dc7b6054e789877f19b7952b3862&transactionId=8dd174f46d143067)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-03-29T20:40:33.890+0000


* Duration: 6 min 8 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages.


- `run integration tests` : Run the Elastic Agent Integration tests.


- `run end-to-end tests` : Generate the packages and run the E2E Tests.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-03-29 21:50 UTC, michel-laterman approved these changes

2022-03-29 21:51 UTC, michel-laterman requested changes

2022-03-29 21:51 UTC, michel-laterman commented on CHANGELOG.next.asciidoc
> +- Fix download verification in snapshot builds. {issue}255[255]
Isn't this a pull: https://github.com/elastic/elastic-agent/pull/255?

2022-03-30 15:26 UTC, ph commented
@michel-laterman Yup, my brain didn't link the right thing :(

2022-03-30 15:50 UTC, michel-laterman approved these changes

2022-03-30 17:31 UTC, merged