[Do not merge] - Use skaffold to run agent in k8s
elastic/elastic-agent pull request #2738
Opened 2023-05-29 07:51 UTC by pchila

## What does this PR do?

Creates a skaffold config along with the necessary bits for (quickly) creating a docker image and manifest transformation for running/debugging agent on a local k8s cluster.

Two profiles `elastic-agent-standalone` and `elastic-agent-managed` have been created to run the agent in both modes.

*Note*: this has been tested with [kind](https://kind.sigs.k8s.io/) and [k3d](https://k3d.io/) but it should work with other local k8s cluster. It can be used also with external clusters, although the details about pushing the agent image on remote docker registries have not yet been worked out.

*Note 2*: the build of the elastic agent image is very hacky at the moment, a better way should be implemented before this change is merged

## Why is it important?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Author's Checklist

- [ ]

## How to test this PR locally

- Install [skaffold](https://skaffold.dev/) and a local k8s cluster of your choice (kind is recommended)
- Fill the necessary env vars in `deploy/skaffold/.env`, using the example below:
  ```
  FLEET_URL=https://<my fleet host>:443
  FLEET_ENROLLMENT_TOKEN=<my enrollment tokebn>
  ES_HOST=https://<my elasticsearch host>:443
  ES_USERNAME=<elasticsearch username>
  ES_PASSWORD=<elasticsearch password>
  ```
- Make sure that your k8s context is pointing to the right (local) cluster
- Run the agent by running `skaffold run -p [elastic-agent-standalone|elastic-agent-managed]` or by using the [google cloud code extension](https://cloud.google.com/code) for your IDE
- Wait for the image to be built and deployed on your cluster
- If you want to debug your code you can run `skaffold debug -p [elastic-agent-standalone|elastic-agent-managed]`. This command modifies the elastic-agent container by adding `dlv` debugger and starting the elastic-agent binary with it so a `dlv` client can be connected to it via port forwarding (provided by default)

## Related issues

- 

## Use cases

## Screenshots

## Logs

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

2023-05-31 17:16 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 98.611% (`71/72`) | :+1: 
Files | 68.273% (`170/249`) | :+1: 
Classes | 67.021% (`315/470`) | :+1: 
Methods | 53.678% (`956/1781`) | :+1: 
Lines | 39.467% (`11013/27904`) | :-1: -0.014
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-06-02 11:29 UTC, michalpristas commented
@pchila are you going to address what we discussed during sync or is this considered final?

2023-06-02 14:59 UTC, belimawr reviewed
The only thing I'm missing is some entry in the developer documentation about how to use this PR, especially mentioning the `.env` files, they are hidden on Unix-like systems, so it will be hart to know they need to be edited.

Even a simple `Readme.md` on `deploy/skaffold` will do.

Nit: many files are missing the blank line at the end.

2023-06-02 15:00 UTC, belimawr requested changes
Updating my review to 'request changes'. We really need some small docs about how to use this.

2023-06-20 13:09 UTC, belimawr approved these changes

2023-06-20 13:09 UTC, belimawr commented on docs/local-k8s-testing.md
> +
```suggestion
```

2023-06-29 08:12 UTC, pchila commented
@michalpristas  the upload of images to a remote image registry works however docker.elastic.co is not a suitable registry as it's not possible to assign a ttl or a cleanup policy to the images we upload there and deleting images is not sokmething that can be done self-service. For the moment we are going to merge this pr as-is just with local k8s cluster support

2023-06-29 11:37 UTC, michalpristas commented on Dockerfile.skaffold
> +ARG AGENT_VERSION=8.9.0-SNAPSHOT
we need to update this with each version bump. 
do you think we can read a file and inject it here?

2023-06-29 11:38 UTC, michalpristas commented on Dockerfile.skaffold
> +ARG GO_VERSION=1.19.9
same as agent version, would be good to have this loaded from .go-version

2023-06-29 11:41 UTC, michalpristas approved these changes
lgtm, please think about options to have go and beat version injected magically

2023-06-29 12:27 UTC, pchila commented
@michalpristas  I will have a look at the options for updating the go version and the base elastic agent image version in a follow-up PR. Opened https://github.com/elastic/elastic-agent/issues/2960 to track this

2023-06-29 12:28 UTC, merged