Add a mutex to paths package to prevent race conditions
elastic/elastic-agent pull request #3243
Opened 2023-08-15 16:16 UTC by AndersonQ

## What does this PR do?

Add a mutex to the `paths` package to prevent race conditions

## Why is it important?

There is a possible race condition on setting and reading information from the package. It was caught on [our tests](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp/detail/PR-3214/6/pipeline/) and, without much investigation, seems rather unlikely to happen in production. Nevertheless it needs to be fixed.

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- ~~[ ] I have added an integration test or an E2E test~~

## How to test this PR locally

Running the test `pkg/component/runtime TestManager_FakeInput_Configure` for `Test / Matrix - PLATFORM = 'aws && aarch64 && gobld/diskSizeGb:200'
`

I tried quickly to reproduce the error locally just by running the test, but the race detector did not fire. Nevertheless, the race condition exists.

## Related issues

N/A

## Logs

```
[2023-08-15T12:18:14.379Z] === Failed

[2023-08-15T12:18:14.379Z] === FAIL: pkg/component/runtime TestManager_FakeInput_Configure (1.99s)

[2023-08-15T12:18:14.379Z]     manager_test.go:998: component state changed: {State:STARTING Message:Starting: spawned pid '40977' Units:map[{UnitType:input UnitID:fake-input}:{State:STARTING Message:Starting: spawned pid '40977' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>}] Features:<nil> FeaturesIdx:0 VersionInfo:{Name: Version: Meta:map[]} expectedUnits:map[{UnitType:0 UnitID:fake-input}:{state:2 configStateIdx:1 config:0xc00049c090 err:<nil> logLevel:4}] expectedFeatures:<nil> expectedFeaturesIdx:1}

[2023-08-15T12:18:14.379Z]     manager_test.go:998: component state changed: {State:HEALTHY Message:Healthy: communicating with pid '40977' Units:map[{UnitType:input UnitID:fake-input}:{State:STARTING Message:Starting: spawned pid '40977' Payload:map[] unitState:0 unitMessage: unitPayload:map[] configStateIdx:0 err:<nil>}] Features:<nil> FeaturesIdx:0 VersionInfo:{Name:fake Version:1.0 Meta:map[input:fake]} expectedUnits:map[{UnitType:0 UnitID:fake-input}:{state:2 configStateIdx:1 config:0xc00049c090 err:<nil> logLevel:4}] expectedFeatures:<nil> expectedFeaturesIdx:1}

[2023-08-15T12:18:14.379Z] {"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"state":"STARTING","expectedState":"HEALTHY","time":"2023-08-15T12:17:41Z","message":"unit change received","level":"info","ecs.version":"1.6.0"}

[2023-08-15T12:18:14.379Z] {"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"trace","time":"2023-08-15T12:17:41Z","message":"registering set_state action for unit","ecs.version":"1.6.0"}

[2023-08-15T12:18:14.379Z] {"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"message":"registering send_event action for unit","level":"trace","time":"2023-08-15T12:17:41Z","ecs.version":"1.6.0"}

[2023-08-15T12:18:14.379Z] {"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"trace","time":"2023-08-15T12:17:41Z","message":"registering kill action for unit","ecs.version":"1.6.0"}

[2023-08-15T12:18:14.379Z] {"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"time":"2023-08-15T12:17:41Z","message":"registering retrieve_features action for unit","level":"trace","ecs.version":"1.6.0"}

[2023-08-15T12:18:14.379Z]     manager_test.go:998: component state changed: {State:HEALTHY Message:Healthy: communicating with pid '40977' Units:map[{UnitType:input UnitID:fake-input}:{State:HEALTHY Message:Fake Healthy Payload:map[] unitState:2 unitMessage:Fake Healthy unitPayload:map[] configStateIdx:1 err:<nil>}] Features:<nil> FeaturesIdx:1 VersionInfo:{Name:fake Version:1.0 Meta:map[input:fake]} expectedUnits:map[{UnitType:0 UnitID:fake-input}:{state:2 configStateIdx:1 config:0xc00049c090 err:<nil> logLevel:4}] expectedFeatures:<nil> expectedFeaturesIdx:1}

[2023-08-15T12:18:14.379Z] {"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"time":"2023-08-15T12:17:41Z","level":"debug","state":"HEALTHY","message":"updating unit state","ecs.version":"1.6.0"}

[2023-08-15T12:18:14.379Z] {"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"trace","kill_on_interval":false,"time":"2023-08-15T12:17:41Z","message":"kill_on_interval config set value","ecs.version":"1.6.0"}

[2023-08-15T12:18:14.379Z] {"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"state":"HEALTHY","expectedState":"HEALTHY","time":"2023-08-15T12:17:41Z","message":"unit change received","level":"info","ecs.version":"1.6.0"}

[2023-08-15T12:18:14.379Z] {"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"trace","kill_on_interval":false,"time":"2023-08-15T12:17:41Z","message":"kill_on_interval config set value","ecs.version":"1.6.0"}

[2023-08-15T12:18:14.379Z] {"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"message":"updating unit state","time":"2023-08-15T12:17:41Z","level":"debug","state":"DEGRADED","ecs.version":"1.6.0"}

[2023-08-15T12:18:14.379Z]     manager_test.go:998: component state changed: {State:HEALTHY Message:Healthy: communicating with pid '40977' Units:map[{UnitType:input UnitID:fake-input}:{State:DEGRADED Message:Fake Degraded Payload:map[] unitState:3 unitMessage:Fake Degraded unitPayload:map[] configStateIdx:2 err:<nil>}] Features:<nil> FeaturesIdx:1 VersionInfo:{Name:fake Version:1.0 Meta:map[input:fake]} expectedUnits:map[{UnitType:0 UnitID:fake-input}:{state:2 configStateIdx:2 config:0xc00049c1b0 err:<nil> logLevel:4}] expectedFeatures:<nil> expectedFeaturesIdx:1}

[2023-08-15T12:18:14.379Z] {"log.level":"error","@timestamp":"2023-08-15T12:17:42.014Z","message":"GRPC client error: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:38367: connect: connection refused\"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"ecs.version":"1.6.0"}

[2023-08-15T12:18:14.379Z] {"log.level":"error","@timestamp":"2023-08-15T12:17:42.014Z","message":"GRPC client error: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:38367: connect: connection refused\""," [...]

2023-08-15 16:45 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-3243/detail/PR-3243/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-3243/detail/PR-3243/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-3243/detail/PR-3243/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-3243/detail/PR-3243/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://elastic-agent_3243.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-08-15T16:06:33.940Z&rangeTo=2023-08-15T16:26:33.940Z&transactionName=BUILD+elastic-agent%2Felastic-agent-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=8f90f326eb071a090862f6d81c93d2d5&transactionId=5f6dab24eb447d78)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-08-15T16:16:33.940+0000


* Duration: 29 min 1 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 6221  |
| Skipped      | 47 |
| Total        | 6268   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :green_heart: Flaky test report
Tests succeeded.



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages.


- `run integration tests` : Run the Elastic Agent Integration tests.


- `run end-to-end tests` : Generate the packages and run the E2E Tests.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-08-15 16:45 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 98.734% (`78/79`) | :+1: 
Files | 67.254% (`191/284`) | :+1: 
Classes | 65.595% (`347/529`) | :+1: 
Methods | 52.48% (`1090/2077`) | :+1: 
Lines | 38.351% (`12466/32505`) | :-1: -0.032
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-08-16 05:42 UTC, elasticmachine commented
Pinging @elastic/elastic-agent (Team:Elastic-Agent)

2023-08-16 05:56 UTC, pierrehilbert commented
Don't forget to add a fragment.

2023-08-21 12:53 UTC, michalpristas reviewed
how are you addressing reading portion of the problem? reading is lockless
i'm also thinking about lock per path

2023-08-21 12:53 UTC, michalpristas commented on internal/pkg/agent/application/paths/common.go
> +	mu = sync.Mutex{}
`mu sync.Mutex` should be fine.
i'd prefer pathLock to be more descriptive of what we're using it for

2023-08-21 13:07 UTC, AndersonQ commented
> how are you addressing reading portion of the problem? reading is lockless i'm also thinking about lock per path, shared lock won't guarantee atomicity but it will slow down startup

it's fixed now.

2023-08-23 02:22 UTC, cmacknz commented
Looking at the stack trace in the race, the race is triggered by test code:

```
[2023-08-15T12:18:14.379Z] WARNING: DATA RACE
[2023-08-15T12:18:14.379Z] Write at 0x0000015625d0 by goroutine 307:
[2023-08-15T12:18:14.379Z]   github.com/elastic/elastic-agent/internal/pkg/agent/application/paths.SetVersionHome()
[2023-08-15T12:18:14.379Z]       /var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/src/github.com/elastic/elastic-agent/internal/pkg/agent/application/paths/common.go:112 +0x54
[2023-08-15T12:18:14.379Z]   github.com/elastic/elastic-agent/pkg/component/runtime.testPaths.func1()
[2023-08-15T12:18:14.379Z]       /var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/src/github.com/elastic/elastic-agent/pkg/component/runtime/manager_test.go:2964 +0x48
[2023-08-15T12:18:14.379Z]   testing.(*common).Cleanup.func1()
[2023-08-15T12:18:14.379Z]       /var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/.gvm/versions/go1.20.7.linux.arm64/src/testing/testing.go:1150 +0x134
[2023-08-15T12:18:14.379Z]   testing.(*common).runCleanup()
[2023-08-15T12:18:14.379Z]       /var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/.gvm/versions/go1.20.7.linux.arm64/src/testing/testing.go:1328 +0x148
[2023-08-15T12:18:14.379Z]   testing.tRunner.func2()
[2023-08-15T12:18:14.379Z]       /var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/.gvm/versions/go1.20.7.linux.arm64/src/testing/testing.go:1570 +0x48
[2023-08-15T12:18:14.379Z]   runtime.deferreturn()
[2023-08-15T12:18:14.379Z]       /var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/.gvm/versions/go1.20.7.linux.arm64/src/runtime/panic.go:476 +0x30
[2023-08-15T12:18:14.379Z]   testing.(*T).Run.func1()
[2023-08-15T12:18:14.379Z]       /var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/.gvm/versions/go1.20.7.linux.arm64/src/testing/testing.go:1629 +0x40
[2023-08-15T12:18:14.379Z] 
[2023-08-15T12:18:14.379Z] Previous read at 0x0000015625d0 by goroutine 346:
[2023-08-15T12:18:14.379Z]   github.com/elastic/elastic-agent/internal/pkg/agent/application/paths.Home()
[2023-08-15T12:18:14.379Z]       /var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/src/github.com/elastic/elastic-agent/internal/pkg/agent/application/paths/common.go:96 +0x90c
[2023-08-15T12:18:14.379Z]   github.com/elastic/elastic-agent/pkg/component/runtime.(*commandRuntime).start()
[2023-08-15T12:18:14.379Z]       /var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/src/github.com/elastic/elastic-agent/pkg/component/runtime/command.go:354 +0x91c
[2023-08-15T12:18:14.379Z]   github.com/elastic/elastic-agent/pkg/component/runtime.(*commandRuntime).Run()
[2023-08-15T12:18:14.379Z]       /var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/src/github.com/elastic/elastic-agent/pkg/component/runtime/command.go:136 +0x34c
[2023-08-15T12:18:14.379Z]   github.com/elastic/elastic-agent/pkg/component/runtime.(*componentRuntimeState).runLoop.func1()
[2023-08-15T12:18:14.379Z]       /var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/src/github.com/elastic/elastic-agent/pkg/component/runtime/runtime.go:137 +0xc4
[2023-08-15T12:18:14.379Z]   github.com/elastic/elastic-agent/internal/pkg/runner.Start.func1()
[2023-08-15T12:18:14.379Z]       /var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/src/github.com/elastic/elastic-agent/internal/pkg/runner/runner.go:69 +0x5c
[2023-08-15T12:18:14.379Z] 
[2023-08-15T12:18:14.380Z] Goroutine 307 (running) created at:
[2023-08-15T12:18:14.380Z]   testing.(*T).Run()
[2023-08-15T12:18:14.380Z]       /var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/.gvm/versions/go1.20.7.linux.arm64/src/testing/testing.go:1629 +0x5b4
[2023-08-15T12:18:14.380Z]   testing.runTests.func1()
[2023-08-15T12:18:14.380Z]       /var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/.gvm/versions/go1.20.7.linux.arm64/src/testing/testing.go:2036 +0x80
[2023-08-15T12:18:14.380Z]   testing.tRunner()
[2023-08-15T12:18:14.380Z]       /var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/.gvm/versions/go1.20.7.linux.arm64/src/testing/testing.go:1576 +0x180
[2023-08-15T12:18:14.380Z]   testing.runTests()
[2023-08-15T12:18:14.380Z]       /var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/.gvm/versions/go1.20.7.linux.arm64/src/testing/testing.go:2034 +0x6a8
[2023-08-15T12:18:14.380Z]   testing.(*M).Run()
[2023-08-15T12:18:14.380Z]       /var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/.gvm/versions/go1.20.7.linux.arm64/src/testing/testing.go:1906 +0x8e0
[2023-08-15T12:18:14.380Z]   main.main()
[2023-08-15T12:18:14.380Z]       _testmain.go:101 +0x2b8
[2023-08-15T12:18:14.380Z] 
[2023-08-15T12:18:14.380Z] Goroutine 346 (running) created at:
[2023-08-15T12:18:14.380Z]   github.com/elastic/elastic-agent/internal/pkg/runner.Start()
[2023-08-15T12:18:14.380Z]       /var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/src/github.com/elastic/elastic-agent/internal/pkg/runner/runner.go:68 +0x24c
[2023-08-15T12:18:14.380Z]   github.com/elastic/elastic-agent/pkg/component/runtime.(*componentRuntimeState).runLoop()
[2023-08-15T12:18:14.380Z]       /var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/src/github.com/elastic/elastic-agent/pkg/component/runtime/runtime.go:135 +0xac
[2023-08-15T12:18:14.380Z]   github.com/elastic/elastic-agent/pkg/component/runtime.newComponentRuntimeState.func1()
[2023-08-15T12:18:14.380Z]       /var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/src/github.com/elastic/elastic-agent/pkg/component/runtime/runtime.go:128 +0x34
```

I think it might be specifically coming from this function changing the value that was read by the command runtime used for the fake components:

https://github.com/elastic/elastic-agent/blob/2675646fd179749eaa0ccb4050352419a423f886/pkg/component/runtime/manager_test.go#L3272-L3290

I'm not actually sure that the mutexes here fix the problem. They guarantee only one goroutine reads or writes at a time, but it gives you no guarantee about the ordering of those reads an writes. 

If one goroutine reads the value and continues on, then another updates it, then the update is effectively lost if the first goroutine never reads the value again. It's like it never happened. I think this is what the race detector is telling us here.

If my understanding of this is correct then:

1. This isn't that urgent to fix because it only happens in tests, although we do want to make the race detector happy eventually.
2. We need to fix the ordering of these RW operations in the tests, which adding locks doesn't fix. Looking at where the goroutines were started it looks like a race between test body and an instance of the runtime manager. This seems strange because just reading the code the ordering actually looks right where the testPaths function is called before the runtime manager gets started:

https://github.com/elastic/elastic-agent/blob/2675646fd179749eaa0ccb4050352419a423f886/pkg/component/runtime/manager_test.go#L169-L176

I would bet that the problem is actually a race from the previous instance of the runtime manager since the paths are all global, every goroutine in this test is reading from the same source. The ordering I suspect is:

1. Test A sets global paths A
2. Test A starts runtime manager which reads paths A
3. Test B sets global paths B

The goroutine from 2 is still running and the race detector thinks it lost the write.

If this is true the fix isn't mutexes, it's to stop using global state. We need to be able to create a set of paths per test. We could do this by having the paths all read from a single structure which can be atomically swapped out or copied. In the example above test A would never see the global paths write from test B because they would each have their own copy of the paths.

2023-08-23 02:23 UTC, cmacknz requested changes
Requesting changes since I don't think locking actually fixes the problem here.

2023-08-23 15:35 UTC, AndersonQ commented
@Mergifyio update

2023-08-25 12:39 UTC, pchila commented
Adding my 2 cents here: instead of locking access, would it be possible to use a [`sync.Once`](https://pkg.go.dev/sync#Once) to initialize whatever is needed and we call it every time on every path ? Wouldn't that solve the concurrency problem by simply initializing stuff the first time anyone calls the correct code path ? We are going to pay a performance penalty (since sync.Once still uses a mutex underneath but may) but at least we don't have to care about the order of calls anymore since initialization will happen exactly once at the first moment that requires it and we could do some benchmarking to see what the actual impact would be...

@cmacknz @AndersonQ  what do you think ?

2023-08-28 15:04 UTC, cmacknz commented
>  least we don't have to care about the order of calls anymore since initialization will happen exactly once at the first moment that requires it and we could do some benchmarking to see what the actual impact would be...

If this works I'm fine with it, not sure that would work with the tests are using this though. They are explicitly trying to override the global paths in each test.

2023-08-28 15:21 UTC, AndersonQ commented
> > least we don't have to care about the order of calls anymore since initialization will happen exactly once at the first moment that requires it and we could do some benchmarking to see what the actual impact would be...
> 
> If this works I'm fine with it, not sure that would work with the tests are using this though. They are explicitly trying to override the global paths in each test.

Using a `[sync.Once](https://pkg.go.dev/sync#Once)` restricts the ability to change the values as needed and I don't believe it's a good restriction to add. Besides I don't believe the calls here are in such a hot path in the agent that the mutex will harm performance

2024-01-08 17:19 UTC, AndersonQ commented
it might happen in the tests, correctly it haven't rendered any test flaky and as per discussion we don't have a fix we agree on. So I'm closing it for now.

2024-01-08 17:19 UTC, closed without merging