Change the selection of downgrade version in TestUpgradeBrokenPackageVersion
elastic/elastic-agent pull request #3458
Opened 2023-09-21 16:03 UTC by pchila

## What does this PR do?
Fixes selection of the elastic agent version to downgrade to in the test so that we don't try to upgrade the agent on its own version

## Why is it important?
The test outcome today depends on the order of versions returned by Artifact API making it flaky when there are some changes.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- 

## Use cases

## Screenshots

## Logs

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

2023-09-21 16:31 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-3458/detail/PR-3458/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-3458/detail/PR-3458/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-3458/detail/PR-3458/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-3458/detail/PR-3458/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://elastic-agent_3458.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-09-21T15:53:22.355Z&rangeTo=2023-09-21T16:13:22.355Z&transactionName=BUILD+elastic-agent%2Felastic-agent-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=926df4cf313a16dba6469622239ab5b1&transactionId=c99d5633530621b4)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-09-21T16:03:22.355+0000


* Duration: 29 min 31 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 6309  |
| Skipped      | 59 |
| Total        | 6368   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :green_heart: Flaky test report
Tests succeeded.



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages.


- `run integration tests` : Run the Elastic Agent Integration tests.


- `run end-to-end tests` : Generate the packages and run the E2E Tests.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-09-22 07:28 UTC, elasticmachine commented
Pinging @elastic/elastic-agent (Team:Elastic-Agent)

2023-09-22 12:14 UTC, AndersonQ approved these changes

2023-09-22 12:14 UTC, AndersonQ commented on testing/integration/upgrade_test.go
> +	// look for 1 version with the current major that is lower than the current one
I'm guessing it's 1 thing? AM I right?

```suggestion
	// transform and reverse the version list and find the most recent version that is different from the broken version returned
	// look for 1 version with the current major that is lower than the current one
```

2023-09-22 12:20 UTC, blakerouse requested changes
This test overall has a problem. Being that this test is downgrading the installed build to a snapshot build, means that when 'elastic-agent uninstall' is ran at the end of the test will be the snapshots uninstall. 

The snapshot uninstall might not have the required code to kill the watcher, which then means the watcher is still running and will break a following test.

2023-09-22 14:57 UTC, pchila commented
@blakerouse since we start from the latest snapshot for test, we don't have that many choices about versions to move to.
The purpose of the test is to ensure that an agent install that has a broken/missing package version file can still be upgraded as [requested when the feature was implemented](https://github.com/elastic/elastic-agent/pull/2908#discussion_r1237153021)
If we cannot downgrade here, what do you suggest? Remove the test entirely? Skip it for a few release cycles?
If we don't merge this PR we still have the test just in the flaky version which is probably a worse outcome

2023-09-25 13:51 UTC, blakerouse commented
> @blakerouse since we start from the latest snapshot for test, we don't have that many choices about versions to move to. The purpose of the test is to ensure that an agent install that has a broken/missing package version file can still be upgraded as [requested when the feature was implemented](https://github.com/elastic/elastic-agent/pull/2908#discussion_r1237153021) If we cannot downgrade here, what do you suggest? Remove the test entirely? Skip it for a few release cycles? If we don't merge this PR we still have the test just in the flaky version which is probably a worse outcome

@pchila We have an overall problem with all the upgrade tests in the integration suite. They are either not testing the actual agent under test (https://github.com/elastic/elastic-agent/issues/3461) or the ending Elastic Agent is an older version of Elastic Agent that might not have required fixes for the testing suite to pass (in this case missing watcher kill).

> @blakerouse would running it in isolation address your concerns? for the time being. once we have previous major with proper watcher capabilities we would go back to normal runs

@michalpristas I wish that would work, but uninstall is a core part of the testing framework. Running this test in isolation will still result in it failing on Windows, because it will not be able to kill the watcher.

Only possible solution is to wait until the watcher is completely done running, before performing the uninstall. I think that is the only valid solution. This is the only case that works, that is still assuming that we don't hit an issue with `RemovePath` on the older version of the Elastic Agent.

2023-09-25 14:34 UTC, cmacknz commented
> @pchila We have an overall problem with all the upgrade tests in the integration suite. They are either not testing the actual agent under test (https://github.com/elastic/elastic-agent/issues/3461) or the ending Elastic Agent is an older version of Elastic Agent that might not have required fixes for the testing suite to pass (in this case missing watcher kill).

Fundamentally to solve this we need the ability to upgrade to the version of the agent that was built in the PR. We need https://github.com/elastic/elastic-agent/issues/2780.

We need to move tests between previously released versions and official snapshots onto a schedule because the code in PRs doesn't affect them at all.


> Only possible solution is to wait until the watcher is completely done running, before performing the uninstall. I think that is the only valid solution. This is the only case that works, that is still assuming that we don't hit an issue with RemovePath on the older version of the Elastic Agent.

Agreed I think this is the only way to deal with this right now, besides skipping the test or figuring out how to unit test this instead of integration testing it.

2023-09-26 06:35 UTC, pchila commented
> Fundamentally to solve this we need the ability to upgrade to the version of the agent that was built in the PR. We need https://github.com/elastic/elastic-agent/issues/2780.

For standalone we mostly do, except for versions of agent where we cannot specify a `file://` source-uri and a `skip-verify` flag. For Fleet managed tests I would expect the same but I didn't actually verify that we do use the packaged version of agent something can be improved there.

For the scope of this PR, do we want to include all of those changes? Or do we create a separate issues/PRs for those ?

2023-09-26 07:43 UTC, pchila commented
@blakerouse @cmacknz Adding the wait means partially revert commit 7e86d24cd336145b9641f621a3de10ed3af0c9fe where the cleanup functions have been removed.
Would that be acceptable for the moment in this PR ?

2023-09-26 14:03 UTC, pchila commented
@blakerouse could you give another review pass now that we have reintroduced the wait for watcher on the upgrade tests ?

2023-09-26 14:22 UTC, pchila commented
@cmacknz 

> We need to move tests between previously released versions and official snapshots onto a schedule because the code in PRs doesn't affect them at all.

https://github.com/elastic/elastic-agent/issues/3475

2023-09-26 17:50 UTC, blakerouse commented
@pchila See my PR #3477

I believe I have upgrade testing working correctly, even this one.

2023-09-28 12:48 UTC, pchila commented
This is replaced by https://github.com/elastic/elastic-agent/pull/3477

2023-09-28 12:48 UTC, closed without merging