Remove the agent version override in tests.
elastic/elastic-agent pull request #3563
Opened 2023-10-06 21:05 UTC by cmacknz

We now have working 8.12.0, 8.11.0, and 8.10.3 snapshots.

2023-10-06 21:05 UTC, elasticmachine commented
Pinging @elastic/elastic-agent (Team:Elastic-Agent)

2023-10-06 21:34 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-3563/detail/PR-3563/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-3563/detail/PR-3563/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-3563/detail/PR-3563/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-3563/detail/PR-3563/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://elastic-agent_3563.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-10-06T20:56:10.644Z&rangeTo=2023-10-06T21:16:10.644Z&transactionName=BUILD+elastic-agent%2Felastic-agent-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=637ff191f8aa832e5cc5bfc660cdd882&transactionId=1aaac7af11f8f03a)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-10-06T21:06:10.644+0000


* Duration: 28 min 55 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 6525  |
| Skipped      | 59 |
| Total        | 6584   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :green_heart: Flaky test report
Tests succeeded.



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages.


- `run integration tests` : Run the Elastic Agent Integration tests.


- `run end-to-end tests` : Generate the packages and run the E2E Tests.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-10-06 21:34 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 98.795% (`82/83`) | :+1: 
Files | 67.114% (`200/298`) | :+1: 
Classes | 65.766% (`365/555`) | :+1: 
Methods | 53.033% (`1154/2176`) | :+1: 
Lines | 38.634% (`13185/34128`) | :+1: 0.035
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-10-09 08:45 UTC, pchila commented
buildkite test this

2023-10-09 08:49 UTC, pchila requested changes
The change is ok but the latest buildkite run is worrying: https://buildkite.com/elastic/elastic-agent/builds/3864

The `TestAPM` and `TestStandaloneUpgradeWithGPGFallback` fail again (symptoms look very similar to the fleet bootstrap issue we already experienced during 8.11.0 FF)

I relaunched an integration test run but this should not be merged until we get a clean run

2023-10-09 18:56 UTC, faec commented
It looks like the explicit test failure is trying to grab a snapshot URL that doesn't exist (maybe it's getting the hash wrong?) but I also noticed this line which looks weird to me:

```
>>> (linux-amd64-ubuntu-2204) Test output (sudo) (stdout): upgrader.go:190: Upgrading from version "8.12.0-SNAPSHOT" to version "8.11.0"
```

Is this an intentional "upgrade" to a lower version, or is the test misbehaving?

2023-10-10 18:35 UTC, cmacknz commented
> the GPG ones look likethey are coming from 8.11.0 not being released but being selected as a version for the downgrade

When we call https://artifacts-api.elastic.co/v1/versions/ it reports that 8.11 is a known version which isn't actually true. Possibly this is because an 8.11 BC exists and we would need to download that.

```json
{"versions":["7.17.10","7.17.11","7.17.12","7.17.13","7.17.14-SNAPSHOT","7.17.14","8.7.1","8.8.0","8.8.1","8.8.2","8.9.0","8.9.1","8.9.2","8.10.0-SNAPSHOT","8.10.0","8.10.1-SNAPSHOT","8.10.1","8.10.2-SNAPSHOT","8.10.2","8.10.3-SNAPSHOT","8.10.3","8.11.0-SNAPSHOT","8.11.0","8.12.0-SNAPSHOT"],"aliases":["7.17-SNAPSHOT","7.17","8.7","8.8","8.9","8.10-SNAPSHOT","8.10","8.11-SNAPSHOT","8.11","8.12-SNAPSHOT"],"manifests":{"last-update-time":"Tue, 10 Oct 2023 18:24:10 UTC","seconds-since-last-update":14}}
```

The problem is it comes from https://staging.elastic.co/8.11.0-8f52d632/summary-8.11.0.html#elastic-agent which we have no special handling for in the agent. This is because there is no obvious qualifier in the version itself to tell us to look in staging like there is for snapshots:

https://github.com/elastic/elastic-agent/blob/7e653ebb09692e4dcf226d8699fd733593eb29dd/internal/pkg/agent/application/upgrade/artifact/download/snapshot/downloader.go#L23

We can either unconditionally use the snapshot version or look at the https://artifacts-api.elastic.co/v1/versions/8.11 to confirm the URL to use. I don't see a reason not to use snapshots since BCs have a larger time window between fixes if we need to fix a problem.

2023-10-10 18:54 UTC, cmacknz commented
I think what we can do is check if the highest version number only has a snapshot available (8.12.0-SNAPSHOT). If it does it is unreleased, and the previous version must also be a snapshot to guarantee it exists.

The only caveat to this is we would prefer 8.11.1-SNAPSHOT to 8.11.0 once 8.11.0 is actually released, but I think that is actually preferable if we are still actively iterating on the code for the 8.11 branch.

2023-10-11 13:08 UTC, cmacknz commented
And now 8.12.0-SNAPSHOT is broken.

2023-10-12 13:52 UTC, cmacknz commented
buildkite test it

2023-10-12 14:22 UTC, pchila approved these changes
The only thing missing is a successful run of integration tests...

2023-10-13 19:53 UTC, cmacknz commented
The RetryDownload upgrade test appears to be failing because of a bug where the the updated source URI is ignored in favour of the snapshot path. Probably this has to do with the fact that a dedicated snapshot downloader exists and gets tried before the http one so this will always fail for snapshots.

```json
{"log.level":"info","@timestamp":"2023-10-12T21:13:48.976Z","log.origin":{"file.name":"upgrade/step_download.go","file.line":59},"message":"Downloading upgrade artifact","log":{"source":"elastic-agent"},"version":"8.11.0-SNAPSHOT","source_uri":"http://localhost:35383","drop_path":"","target_path":"/opt/Elastic/Agent/data/elastic-agent-f0c25c/downloads","install_path":"/opt/Elastic/Agent/data/elastic-agent-f0c25c/install","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-10-12T21:13:48.976Z","log.origin":{"file.name":"upgrade/step_download.go","file.line":188},"message":"download attempt 1","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-10-12T21:14:26.665Z","log.origin":{"file.name":"http/downloader.go","file.line":319},"message":"download from https://snapshots.elastic.co/8.11.0-60b804d4/downloads/beats/elastic-agent/elastic-agent-8.11.0-SNAPSHOT-linux-arm64.tar.gz completed in 37 seconds @ 17.52MBps","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-10-12T21:14:26.727Z","log.origin":{"file.name":"http/downloader.go","file.line":319},"message":"download from https://snapshots.elastic.co/8.11.0-60b804d4/downloads/beats/elastic-agent/elastic-agent-8.11.0-SNAPSHOT-linux-arm64.tar.gz.sha512 completed in Less than a second @ +InfYBps","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
```

2023-10-16 17:45 UTC, merged