[CI] Pull requests migration to buildkite
elastic/elastic-agent pull request #3573
Opened 2023-10-09 20:49 UTC by pazone

## What does this PR do?
Migrates pull request workflow to buildkite

- Relates https://github.com/elastic/ingest-dev/issues/1710

2023-10-09 21:15 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-3573/detail/PR-3573/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-3573/detail/PR-3573/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-3573/detail/PR-3573/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-3573/detail/PR-3573/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://elastic-agent_3573.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-10-09T20:39:47.556Z&rangeTo=2023-10-09T20:59:47.556Z&transactionName=BUILD+elastic-agent%2Felastic-agent-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=dc2b6f03b99c9b7cd41265ee6642f390&transactionId=a7922d5f0ecfc1b6)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-10-09T20:49:47.556+0000


* Duration: 25 min 17 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 6525  |
| Skipped      | 59 |
| Total        | 6584   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :green_heart: Flaky test report
Tests succeeded.



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages.


- `run integration tests` : Run the Elastic Agent Integration tests.


- `run end-to-end tests` : Generate the packages and run the E2E Tests.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-10-09 21:15 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 98.795% (`82/83`) | :+1: 
Files | 67.114% (`200/298`) | :+1: 
Classes | 65.766% (`365/555`) | :+1: 
Methods | 53.033% (`1154/2176`) | :+1: 
Lines | 38.616% (`13179/34128`) | :-1: -0.003
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-10-27 09:14 UTC, dliappis reviewed
Thank you for this massive work!
Basically LGTM from me, left some minor comments.

Is https://buildkite.com/elastic/elastic-agent/builds/4389 an example run where we can see this work in operation?

2023-10-27 14:13 UTC, pazone commented on .buildkite/hooks/post-checkout.ps1
> +function Checkout-Merge {
That's cool! I'd like to try it in my next pull request. I need to land it today somehow :)

2023-10-27 14:16 UTC, pazone commented on .buildkite/scripts/steps/merge.sh
> +set -exuo pipefail
I think yes. I prefer the `-x` unless we use any secrets

2023-10-27 14:53 UTC, michalpristas approved these changes
from what i can tell it looks good. 
thanks for making upgrade more stable

2023-10-27 20:36 UTC, cmacknz commented on internal/pkg/agent/application/upgrade/upgrade.go
> +	copyConcurrency := 1
I changed this a bit, if I merge https://github.com/elastic/elastic-agent/pull/3653 before you merge this you'll have a conflict to resolve.

2023-10-30 13:30 UTC, blakerouse requested changes
Overall the changes to make this run under buildkite look great. Only issue I see and the reason I am making it a blocker is because the RACE_DETECTOR was not enabled, something that we need to keep enabled when running the unit tests.

2023-10-30 13:30 UTC, blakerouse commented on .ci/Jenkinsfile
> -                    withEnv(["RACE_DETECTOR=true", "TEST_COVERAGE=${isCodeCoverageEnabled()}"]) {
Looks like the `RACE_DETECTOR=true` is removed in the buildkite jobs. That needs to stay enabled.

2023-10-30 13:52 UTC, blakerouse approved these changes
Thanks for enabling the race detector. Looks good now.

2023-10-30 14:44 UTC, merged

2023-10-30 15:25 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-3573/detail/PR-3573/55//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-3573/detail/PR-3573/55//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-3573/detail/PR-3573/55//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-3573/detail/PR-3573/55//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://elastic-agent_3573.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-10-30T13:41:36.919Z&rangeTo=2023-10-30T14:01:36.919Z&transactionName=BUILD+elastic-agent%2Felastic-agent-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=56fab48683630efdaf1b2461d1ca4581&transactionId=a045fa3ac43ff051)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-10-30T13:51:36.919+0000


* Duration: 94 min 46 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 4941  |
| Skipped      | 57 |
| Total        | 4998   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :green_heart: Flaky test report
Tests succeeded.



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages.


- `run integration tests` : Run the Elastic Agent Integration tests.


- `run end-to-end tests` : Generate the packages and run the E2E Tests.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->