Fix a bunch of errorlint errors from our linters
elastic/elastic-agent pull request #360
Opened 2022-04-21 18:51 UTC by ph

This fixes a lot of the error detecting by our linters, this skip the
errors related to the errors packages, we should refactor the usage or
our package instead.

## What does this PR do?

## Why is it important?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- 

## Use cases

## Screenshots

## Logs

2022-04-21 18:51 UTC, ph commented
/test

2022-04-21 18:54 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > There is a new build on-going so the previous on-going builds have been aborted.
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-360/detail/PR-360/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-360/detail/PR-360/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-360/detail/PR-360/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-360/detail/PR-360/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2022-04-21T18:41:31.646Z&rangeTo=2022-04-21T19:01:31.646Z&transactionName=elastic-agent/elastic-agent-mbp/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=d480aab5c55c6b5c4fc58722be2a8f99&transactionId=7159342d27b16f67)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-04-21T18:51:31.646+0000


* Duration: 3 min 52 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-360/detail/PR-360/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/elastic-agent/pipelines/elastic-agent-mbp/pipelines/PR-360/runs/1/steps/95/log/?start=0">here</a></li>
<li>Description: <code>tar: step failed with error null</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages.


- `run integration tests` : Run the Elastic Agent Integration tests.


- `run end-to-end tests` : Generate the packages and run the E2E Tests.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-25 14:39 UTC, ph commented on Makefile
> -	@mage check
This shouldn't be here, this actually makes the linter run twice and it should only be run by the github action.

2022-04-25 18:39 UTC, ph commented
/test

2022-04-26 12:00 UTC, AndersonQ requested changes
I think you might have misses a `!` on a if statement. I commented there

2022-04-26 12:26 UTC, ph commented on internal/pkg/agent/operation/operator.go
> +		if errors.Is(err, context.Canceled) {
I think you are correct here, the filtering is non-obvious I was misled by it.

2022-04-27 08:18 UTC, AndersonQ approved these changes
you still have failing tests, but so far so good :)

2022-04-27 12:17 UTC, ph commented
@AndersonQ well the linter... is a work in progress. I think the next one is the errcheck.
@mdelapenya or @ChrsMark I see an e2e test failing on k8s, Is this a known issue or I should investigate it?

```

[2022-04-26T14:24:10.545Z]     Then "elastic-agent" collects events with "kubernetes.pod.name:redis" # autodiscover_test.go:295 -> *podsManager

[2022-04-26T14:24:10.545Z]     context deadline exceeded

[2022-04-26T14:24:10.545Z] TRAC[2022-04-26T14:24:09Z] Executing command                             args="[export logs --name kind-a2627034-35d0-4f57-9620-83f7ceb14414 /home/admin/e2e-testing/outputs/kubernetes-autodiscover/kind-a2627034-35d0-4f57-9620-83f7ceb14414]" command=kind env="map[]"

[2022-04-26T14:24:10.546Z] TRAC[2022-04-26T14:24:09Z] Output                                        output=/home/admin/e2e-testing/outputs/kubernetes-autodiscover/kind-a2627034-35d0-4f57-9620-83f7ceb14414

[2022-04-26T14:24:10.546Z] INFO[2022-04-26T14:24:09Z] Kind cluster logs exported                    cluster=kind-a2627034-35d0-4f57-9620-83f7ceb14414 path=/home/admin/e2e-testing/outputs/kubernetes-autodiscover/kind-a2627034-35d0-4f57-9620-83f7ceb14414

[2022-04-26T14:24:10.546Z] TRAC[2022-04-26T14:24:09Z] Executing command                             args="[delete cluster --name kind-a2627034-35d0-4f57-9620-83f7ceb14414]" command=kind env="map[]"

[2022-04-26T14:24:11.932Z] TRAC[2022-04-26T14:24:11Z] Output                                        output=

[2022-04-26T14:24:11.932Z] INFO[2022-04-26T14:24:11Z] kind cluster  was deleted                    

[2022-04-26T14:25:19.687Z] 

[2022-04-26T14:25:19.687Z] --- Failed steps:

[2022-04-26T14:25:19.687Z] 

[2022-04-26T14:25:19.687Z]   Scenario: Logs collection from running pod # features/elastic_agent_standalone.feature:9

[2022-04-26T14:25:19.687Z]     Then "elastic-agent" collects events with "kubernetes.pod.name:a-pod" # features/elastic_agent_standalone.feature:12

[2022-04-26T14:25:19.687Z]       Error: context deadline exceeded

[2022-04-26T14:25:19.687Z] 

[2022-04-26T14:25:19.687Z]   Scenario: Logs collection from a pod with an init container # features/elastic_agent_standalone.feature:14

[2022-04-26T14:25:19.687Z]     Then "elastic-agent" collects events with "kubernetes.container.name:init-container" # features/elastic_agent_standalone.feature:17

[2022-04-26T14:25:19.687Z]       Error: context deadline exceeded

[2022-04-26T14:25:19.687Z] 

[2022-04-26T14:25:19.687Z]   Scenario: Logs collection from short-living cronjobs # features/elastic_agent_standalone.feature:22

[2022-04-26T14:25:19.687Z]     Then "elastic-agent" collects events with "kubernetes.container.name:cronjob-container" # features/elastic_agent_standalone.feature:26

[2022-04-26T14:25:19.687Z]       Error: context deadline exceeded

[2022-04-26T14:25:19.687Z] 

[2022-04-26T14:25:19.687Z]   Scenario: Logs collection from failing pod # features/elastic_agent_standalone.feature:28

[2022-04-26T14:25:19.687Z]     Then "elastic-agent" collects events with "kubernetes.pod.name:a-failing-pod" # features/elastic_agent_standalone.feature:31

[2022-04-26T14:25:19.687Z]       Error: context deadline exceeded

[2022-04-26T14:25:19.687Z] 

[2022-04-26T14:25:19.687Z]   Scenario: Metrics collection configured from targeted Redis Pod # features/elastic_agent_standalone.feature:33

[2022-04-26T14:25:19.687Z]     Then "elastic-agent" collects events with "kubernetes.pod.name:redis" # features/elastic_agent_standalone.feature:36

[2022-04-26T14:25:19.687Z]       Error: context deadline exceeded

[2022-04-26T14:25:19.687Z] 
```

2022-04-27 13:07 UTC, mdelapenya commented
> @AndersonQ well the linter... is a work in progress. I think the next one is the errcheck. @mdelapenya or @ChrsMark I see an e2e test failing on k8s, Is this a known issue or I should investigate it?

The team is working on it, thanks for the ping!

2022-04-27 13:10 UTC, merged