use crypto.rand in generate id with ulid.
elastic/elastic-agent pull request #370
Opened 2022-04-25 20:10 UTC by ph

## What does this PR do?
This removes the usage of `math.rand` as the source of random data for generating ulid, this remove one of the gosec warning.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- 

## Use cases

## Screenshots

## Logs

2022-04-25 20:29 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-370/detail/PR-370/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-370/detail/PR-370/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-370/detail/PR-370/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp%2FPR-370/detail/PR-370/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://elastic-agent_370.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2022-04-25T20:00:30.205Z&rangeTo=2022-04-25T20:20:30.205Z&transactionName=elastic-agent/elastic-agent-mbp/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=86818e66f5c523129bbac83ad2018e47&transactionId=b982db931900a724)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-04-25T20:10:30.205+0000


* Duration: 19 min 9 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 3849  |
| Skipped      | 21 |
| Total        | 3870   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages.


- `run integration tests` : Run the Elastic Agent Integration tests.


- `run end-to-end tests` : Generate the packages and run the E2E Tests.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-26 12:11 UTC, AndersonQ requested changes
I added a comment, please take a look.

2022-04-26 12:11 UTC, AndersonQ commented on internal/pkg/id/generate_test.go
> +	}
[Question/Suggestion]

I wonder if it makes sense to have this test. I'm not a expert in maths or cryptography, but here are my 2 cents:
 - the randomness of the UUIDs are determined by `crypto/rand` and  `github.com/oklog/ulid`. We should not need to test them.
 - you're only guaranteeing it does not generates 2 equal UUIDs in sequence, any other combination it'll not catch. E.g. A-B-A
 - I'm not convinced only 1000 are enough runs to prove or guarantee anything.
 
 I believe this test misleads more than it adds. it misleads in the sense it seems to ensure the randomness is good, when I don't believe it does, and it deviates the test from ensuring the implementation of `Generate` function works. I believe a better test would be to ensure the returned value is non nil, that when transformed into string it has got the expected format. That'd ensure that even if the implementation is changed, if the `ID` is redefined, nothing breaks.

2022-04-26 12:25 UTC, ph commented
@AndersonQ You are completely right on the above, I've put the old test back here.

2022-04-27 12:22 UTC, merged