Fix (*artifact.Config).Unpack not preserving not overridden values
elastic/elastic-agent pull request #3930
Opened 2023-12-19 19:10 UTC by AndersonQ

## What does this PR do?

(*artifact.Config).Unpack was creating a new instance of Config and manually coping all values from the original to the new one. New values added to config, RetrySleepInitDuration in this case, were neither maintaining its default value nor being updated with the new value. Now it uses reflection to ensure all values are correctly copied.

## Why is it important?

When applying a new `agent.download` config some of the default values were set to the zero value and even if they'd come on the new fleet config, they'd be ignored.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- ~~[ ] I have added an integration test or an E2E test~~

## How to test this PR locally
Try any of the following:
 - Copy the test `TestConfig_Unpack` to main and see it failing.
 - Set the `retry_sleep_init_duration` in the agent's policy, enrol it to fleet and check it's not set.
 - Reproduce the issue described in #3914

## Related issues

- Closes #3914

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

2023-12-19 19:10 UTC, elasticmachine commented
Pinging @elastic/elastic-agent (Team:Elastic-Agent)

2023-12-19 19:22 UTC, cmacknz commented
> *artifact.Config).Unpack was creating a new instance of Config and manually coping all values from the original to the new one. 

Do we know why it was doing this? Are there any hints in the commit history? This seems intentional so I am wondering if this was because of a bug or something from the past.

2023-12-19 19:24 UTC, cmacknz commented
Ah the answer is the comment, thanks!

2023-12-19 19:34 UTC, blakerouse approved these changes
This is just nasty. Really sucks that this needs to be done this way. I think the way you handled it is the best way to go currently.

Really glad you added a test to ensure those structures stay inline.

2023-12-19 20:16 UTC, cmacknz commented
Since we need to special case the transport, which includes the proxy configuration, I wonder if we should implement https://github.com/elastic/elastic-agent/issues/3820 as part of this PR to ensure we didn't break it. 

It's already in the current sprint and assigned to Anderson anyway.

2023-12-20 06:08 UTC, AndersonQ commented
buildkite test this

2023-12-20 07:41 UTC, pierrehilbert commented
` invalid character 'E' looking for beginning of value`

Could it be something coming from your change?

2023-12-20 08:06 UTC, belimawr requested changes

2023-12-20 10:21 UTC, jlind23 commented
@AndersonQ will you also tackle https://github.com/elastic/elastic-agent/issues/3820 as suggested by Craig abovE?

2023-12-20 11:13 UTC, belimawr approved these changes

2023-12-20 13:11 UTC, AndersonQ commented
> @AndersonQ will you also tackle https://github.com/elastic/elastic-agent/issues/3820 as suggested by Craig abovE?

Not in this PR

2023-12-20 21:16 UTC, cmacknz commented on internal/pkg/agent/application/upgrade/artifact/config.go
> +		}
Thanks for catching this, this suggests there is a test case missing to catch this.

2023-12-29 10:16 UTC, AndersonQ commented
buildkite test this

2024-01-02 13:08 UTC, merged