wip
elastic/elastic-agent pull request #5044
Opened 2024-07-02 23:55 UTC by michel-laterman

## What does this PR do?

Inject `proxy_url` value into output configuration if attribute is missing and `HTTPS_PROXY/HTTP_PROXY` env var is set.

## Why is it important?

Go HTTP clients automatically use various proxy env vars. This leads to inconsistent behaviour where some components get config from the environment, but others do not.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Disruptive User Impact

## How to test this PR locally

## Related issues

- Closes #2602

2024-07-03 13:44 UTC, blakerouse requested changes
Reading the issue this seems like this should also be endpoint specific, so you should really be filter this only to the endpoint component. I don't think we want this to be done across the board, as passing the ENV down to the subprocesses already does the correct thing.

I believe there is already a endpoint specific component modifier, it might be better to integrate this there so multiple modifiers are not needed, each looping through all components and units each time.

See comment amount elasticsearch specific, we should ensure it also works for logstash. Format might be different.

2024-07-03 13:44 UTC, blakerouse commented on internal/pkg/agent/application/inject_proxy_component_modifier.go
> +	}
This means that the `HTTPS_PROXY` will take over the `HTTP_PROXY` even in the case that `HTTPS_PROXY` is set to `""`. That might not be the behavior wanted, might be better to use:

```suggestion
	proxyURL := os.Getenv("HTTPS_PROXY")
	if proxyURL == "" {
		proxyURL = os.LookupEnv("HTTP_PROXY")
	}
```

2024-07-03 13:44 UTC, blakerouse commented on internal/pkg/agent/application/inject_proxy_component_modifier.go
> +					if unit.Type == client.UnitTypeOutput {
This is going to apply to all output types not just elasticsearch. Based on the logic here I believe this should be elasticsearch specific? Would we have a logstash one?

2024-07-03 13:44 UTC, blakerouse commented on internal/pkg/agent/application/inject_proxy_component_modifier.go
> +						}
I assume this is the case even when `proxy_url: ""` in the configuration? I think that makes sense, but we should make that clear in the code comment.

2024-07-03 19:38 UTC, elasticmachine commented
Pinging @elastic/elastic-agent-control-plane (Team:Elastic-Agent-Control-Plane)

2024-07-03 19:41 UTC, blakerouse approved these changes
Thanks for scoping this to endpoint and elasticsearch only. Good test coverage as well, nice!

2024-07-03 20:02 UTC, michel-laterman commented
@intxgo @ferullo
Any concerns about this approach?

2024-07-05 10:13 UTC, intxgo commented
> @intxgo @ferullo Any concerns about this approach?

The PR is incomplete, Endpoint requires fleet proxy as well. I guess that environment proxy also overrides fleet connection on Agent.

However, I'm concerned about the configuration update flow. Endpoint is caching permanently received config so that even if Agent gets compromised the machine remains protected by Endpoint (using last known configuration).

The configuration update protocol is using state index value to determine if the Expected and Actual config are the same or different, so I guess to have the proxy override applied the index would have to be bumped. Is the index solely managed by Agent or is it a Fleet policy property?

https://github.com/elastic/elastic-agent-client/blob/94f110545198e910527a9db7e1a21f8553d70ea2/elastic-agent-client.proto#L185-L201

2024-07-05 21:48 UTC, michel-laterman commented
Thanks @intxgo,
I've added a proxy_url injection into `InjectFleetConfigComponentModifier` to handle that area

2024-07-08 13:45 UTC, intxgo approved these changes

2024-07-08 20:08 UTC, merged