Remove Agent override version in integration tests
elastic/elastic-agent pull request #5119
Opened 2024-07-11 17:28 UTC by pchila

We used to override the agent version to a previous version between the version bump for a new release and the availability of the first snapshot build (usually a period of a few days) because Fleet had a limitation about not accepting agent versions more recent than itself.

This limitation should have been removed by now so we can get rid of the agent version override and use the default agent version

## What does this PR do?

## Why is it important?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Disruptive User Impact

## How to test this PR locally

## Related issues

-

## Questions to ask yourself

- How are we going to support this in production?
- How are we going to measure its adoption?
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

2024-07-11 17:28 UTC, elasticmachine commented
Pinging @elastic/elastic-agent-control-plane (Team:Elastic-Agent-Control-Plane)

2024-07-12 03:36 UTC, jlind23 approved these changes

2024-07-12 03:36 UTC, jlind23 commented
Buildkite test it

2024-07-12 07:23 UTC, pierrehilbert requested changes
We shouldn't remove all those parts according to me.

2024-07-12 07:23 UTC, pierrehilbert commented on .buildkite/scripts/steps/integration_tests.sh
> -OVERRIDE_AGENT_PACKAGE_VERSION="$(cat .package-version)"
I don't think we should stop doing that!
We need https://github.com/elastic/elastic-agent/pull/5100 to be merged instead.

2024-07-12 08:35 UTC, pchila commented
@pierrehilbert This PR came after a discussion in the elastic-agent control plane weekly meeting about #5096 where we determined that Fleet should be able to handle a version of elastic-agent newer than itself.

If Fleet is able to manage a newer agent we don't need to package elastic-agent with a previous version after the version bump. If we still need to use an older stack version on cloud that should be accomplished by specifying `AGENT_STACK_VERSION` when running the tests... Maybe that is the reason why you say we still need this code ?

/cc @cmacknz @ycombinator

2024-07-12 08:49 UTC, pierrehilbert commented
Yes indeed my objective here is to ensure we can have our tests green even if the new stack version is not available on our cloud.
But if you have another idea, I'm ofc opened to it.

2024-07-12 12:17 UTC, pchila commented
@pierrehilbert  what you is probably what is in commit 83a3a830df4dcea100c13b33f3fea06003ba5daf
Please have another look

2024-07-12 12:21 UTC, pierrehilbert approved these changes
Thanks for switching AGENT_VERSION to AGENT_STACK_VERSION as this is what we will need in the future.

2024-07-15 06:17 UTC, andrzej-stencel approved these changes

2024-07-15 09:35 UTC, merged