refactor: replace go-acl with upstream x/sys/windows package
elastic/elastic-agent pull request #5282
Opened 2024-08-10 15:09 UTC by kruskall

## What does this PR do?

drop go-acl dependency and use upstream functions from x/sys/windows

## Why is it important?

recent versions of x/sys/windows added necessary functions to replace go-acl. 

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Disruptive User Impact

## How to test this PR locally

## Related issues

-

## Questions to ask yourself

- How are we going to support this in production?
- How are we going to measure its adoption?
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

2024-08-10 16:03 UTC, elasticmachine commented
Pinging @elastic/elastic-agent-control-plane (Team:Elastic-Agent-Control-Plane)

2024-08-12 15:30 UTC, blakerouse approved these changes
Really nice! Much appreciated.

2024-08-16 13:50 UTC, blakerouse reviewed
This seems like it has an actual issue in it:

```
Error: error installing package: failed to perform permission changes on path C:\Program Files\Elastic\Agent: The parameter is incorrect.
```

2024-08-19 14:17 UTC, blakerouse requested changes
Marking this as request changes because there is definitely an error case that is occurring (but seems like a race).

```
[=   ] Successfully copied files  [3s] Error uninstalling. Printing logs
        Error: error installing package: failed to perform permission changes on path C:\Program Files\Elastic\Agent: The parameter is incorrect.
        For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.16/fleet-troubleshooting.html
    install_test.go:324: 
        	Error Trace:	C:/Users/windows/agent/testing/integration/install_test.go:324
        	Error:      	Received unexpected error:
        	            	error running agent install command: exit status 1
        	Test:       	TestRepeatedInstallUninstall/TestRepeatedInstallUninstall-22
--- FAIL: TestRepeatedInstallUninstall/TestRepeatedInstallUninstall-22 (11.34s)
```

2024-08-19 22:12 UTC, blakerouse commented
Actually I might be wrong and this is an issue even today with the Elastic Agent. See this PR - https://github.com/elastic/elastic-agent/pull/5317

Probably need to ensure that the PR change is not lost when its merged and then this one is merged.

2024-08-19 23:41 UTC, michel-laterman commented on internal/pkg/agent/perms/windows.go
> +	return windows.SetNamedSecurityInfo(
I just merged https://github.com/elastic/elastic-agent/pull/5317 which checked that `acl.Apply` did not return `syscall.Errno(0)`
I think you would need to make a similar check here, I'm not sure if `windows.ACLFromEntries` would need the same check or not

2024-08-21 13:34 UTC, blakerouse commented
The error here is a little different then the other PR I mentioned previously:

` Error: error installing package: failed to perform permission changes on path C:\Elastic\Agent-Testing: The parameter is incorrect.`

Something is incorrect in this PR that is causing the `The parameter is incorrect`.

2025-02-18 07:30 UTC, jlind23 commented
Cleaning up the elastic agent repo, closing this PR for now please reopen if required.

2025-02-18 07:30 UTC, closed without merging