Emit Pod data only for running Pods in the Kubernetes provider
elastic/elastic-agent pull request #6011
Opened 2024-11-13 12:36 UTC by swiatekm

## What does this PR do?

The kubernetes provider emits data each time a Pod gets updated, even if the Pod is not yet running. As a result, every time a new Pod is spawned, we get multiple updates as it is created, scheduled, containers are created, and so on. Instead, emit the data only if the Pod is actually running.

## Why is it important?

Configuration reloading can be quite expensive when there are a lot of Pods on the Node. We should avoid doing so unnecessarily. This change should help #5835 and #5991.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)

## How to test this PR locally

## Related issues

- Relates #5835
- Relates #5991

2024-11-13 15:02 UTC, pkoutsovasilis approved these changes
This change makes sense to me; LGTM

2024-11-13 15:19 UTC, gizas commented
@swiatekm thanks for this. This makes sense.

I want to make sure some corner cases like:
- pods created from cronjobs
- pods that are restarting (eg. OOM or Imagepull error) how this will behave in such cases?

2024-11-13 15:39 UTC, blakerouse commented
> > @swiatekm thanks for this. This makes sense.
> > I want to make sure some corner cases like:
> > ```
> > * pods created from cronjobs
> > ```
> 
> There isn't really any difference. It's possible for the Pod to be finished running before we update the configuration, but this is possible right now too. I'm not sure if this is a problem either way - scrapers probably wouldn't get any metrics, and container logs should remain for filelog to read until the Pod is deleted.

We actually delay the removal of a pod after it is stopped to ensure that it exists for a period of time. This is needed for reading the log files for a reason (think nginx access logs from inside of the container). I think this should handle the case where the status is basically greater than > Running. As in crashed, stopping, stopped, etc.

2024-11-13 15:59 UTC, swiatekm commented
For the record, I considered other approaches to this problem, but trying to debounce the updates in a more clever way made things more difficult to reason about and ultimately not much better than the current solution.

2024-11-13 19:10 UTC, blakerouse requested changes

2024-11-18 11:07 UTC, gizas approved these changes

2024-11-18 12:57 UTC, merged