feat: drop init.d support and go-daemon binaries
elastic/elastic-agent pull request #6174
Opened 2024-12-02 05:28 UTC by kruskall

## What does this PR do?

remove init.d scripts
drop go-daemon dep and daemon binaries
cleanup mage tasks

## Why is it important?

Similar to https://github.com/elastic/beats/pull/41845

init.d should not be needed on distros we support
According to go-daemon readme: "Go daemon is not needed on systems with [systemd](http://www.freedesktop.org/wiki/Software/systemd/)."

See https://www.elastic.co/support/matrix#matrix_os

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Disruptive User Impact

## How to test this PR locally

## Related issues

-

## Questions to ask yourself

- How are we going to support this in production?
- How are we going to measure its adoption?
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

2024-12-02 07:48 UTC, elasticmachine commented
Pinging @elastic/elastic-agent-control-plane (Team:Elastic-Agent-Control-Plane)

2024-12-05 15:42 UTC, kaanyalti approved these changes

2024-12-05 23:50 UTC, kaanyalti submitted a review, later dismissed
Code changes look good to me, but I don't have enough context here, if someone else can look at it as well it would be better.

2024-12-06 16:20 UTC, cmacknz commented
This is fine as long as the DEB and RPM packages still run as services. That there is no replacement systemd unit file added here makes me think we may have broken something. I see the DEB tests are failing now, so that is one potential reason.

We create out existing systemd service in Go code right now so there isn't an easy way to extract it without refactoring that. https://github.com/elastic/elastic-agent/blob/54932dc7b46cdd0d16791e07b8fc5dd596efb129/internal/pkg/agent/install/svc.go#L84

2024-12-11 15:51 UTC, blakerouse requested changes
I think this change is possible because it is true that on DEB/RPM that we do not support any OS that uses sysvinit. But there is clearly an issue with the upgrade path for the deb packages.

Interested to determine what you find on why that is not working with these changes. I am going to mark this as "Request changes" only, because I was to review it again before its merged with that fixed.

2025-02-14 21:31 UTC, cmacknz commented
There is an actual bug related to us continuing to include init.d files now https://github.com/elastic/elastic-agent/issues/6704

2025-02-28 05:13 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/elastic-agent/builds/17705)
* Commit: 24571b5e31dd8dd7c689f61c7eb3491074f8d19a

### Failed CI Steps
* [Unit tests - Windows 10](https://buildkite.com/elastic/elastic-agent/builds/17705#01954ae6-aa23-4d0b-8155-5f997fb0528e)

cc @kruskall

<!--buildkite-pr-comment-elastic-agent
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-agent/builds/17705","number":17705,"commit":"24571b5e31dd8dd7c689f61c7eb3491074f8d19a"}],"number":17705}
buildkite-pr-comment-->

2025-03-06 02:25 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/elastic-agent/builds/18182)
* Commit: 7c5eb7e27e5f0fca412e110b40021226759b3e12

### Failed CI Steps
* [Unit tests - Windows 2016](https://buildkite.com/elastic/elastic-agent/builds/18182#01956913-8046-4471-aa56-af255f287a18)
* [x86_64:sudo: deb](https://buildkite.com/elastic/elastic-agent/builds/18182#0195692c-7bb7-49e8-a42e-719c703ca051)
* [x86_64:sudo: deb](https://buildkite.com/elastic/elastic-agent/builds/18182#01956939-5b54-486f-a5d1-617d5cb5a0fe)
* [x86_64:sudo:rpm](https://buildkite.com/elastic/elastic-agent/builds/18182#0195692c-7bbd-4242-ac55-0d37a57afb18)

### History
* :broken_heart: [Build #17705](https://buildkite.com/elastic/elastic-agent/builds/17705) failed 24571b5e31dd8dd7c689f61c7eb3491074f8d19a

cc @kruskall

<!--buildkite-pr-comment-elastic-agent
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/elastic-agent/builds/18182","number":18182,"commit":"7c5eb7e27e5f0fca412e110b40021226759b3e12"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-agent/builds/17705","number":17705,"commit":"24571b5e31dd8dd7c689f61c7eb3491074f8d19a"}],"number":18182}
buildkite-pr-comment-->

2025-04-18 03:20 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/elastic-agent/builds/20214)
* Commit: 484b906e5cc5a57ddbd7a730562c64f0f45438e9

### Failed CI Steps
* [x86_64:sudo: deb](https://buildkite.com/elastic/elastic-agent/builds/20214#019646d0-0e39-481e-8a00-0ad5fdd031bb)
* [x86_64:sudo: deb](https://buildkite.com/elastic/elastic-agent/builds/20214#019646dc-9af5-4409-88f9-6b78d62457cb)

### History
* :broken_heart: [Build #18182](https://buildkite.com/elastic/elastic-agent/builds/18182) failed 7c5eb7e27e5f0fca412e110b40021226759b3e12
* :broken_heart: [Build #17705](https://buildkite.com/elastic/elastic-agent/builds/17705) failed 24571b5e31dd8dd7c689f61c7eb3491074f8d19a

cc @kruskall

<!--buildkite-pr-comment-elastic-agent
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/elastic-agent/builds/20214","number":20214,"commit":"484b906e5cc5a57ddbd7a730562c64f0f45438e9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/elastic-agent/builds/18182","number":18182,"commit":"7c5eb7e27e5f0fca412e110b40021226759b3e12"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-agent/builds/17705","number":17705,"commit":"24571b5e31dd8dd7c689f61c7eb3491074f8d19a"}],"number":20214}
buildkite-pr-comment-->

2025-04-22 16:18 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/elastic-agent/builds/20330)
* Commit: 7c131517dc4a8ca656d3cfd6324e6abafe556f74

### Failed CI Steps
* [x86_64:sudo: deb](https://buildkite.com/elastic/elastic-agent/builds/20330#01965e30-9419-4ac5-aa85-2e5b8c19ef7b)
* [x86_64:sudo: deb](https://buildkite.com/elastic/elastic-agent/builds/20330#01965e3c-52b5-48e5-901d-6116f5e64e8e)

### History
* :broken_heart: [Build #20214](https://buildkite.com/elastic/elastic-agent/builds/20214) failed 484b906e5cc5a57ddbd7a730562c64f0f45438e9
* :broken_heart: [Build #18182](https://buildkite.com/elastic/elastic-agent/builds/18182) failed 7c5eb7e27e5f0fca412e110b40021226759b3e12
* :broken_heart: [Build #17705](https://buildkite.com/elastic/elastic-agent/builds/17705) failed 24571b5e31dd8dd7c689f61c7eb3491074f8d19a

cc @kruskall

<!--buildkite-pr-comment-elastic-agent
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/elastic-agent/builds/20330","number":20330,"commit":"7c131517dc4a8ca656d3cfd6324e6abafe556f74"},{"buildStatus":{"state":"failing","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/elastic-agent/builds/20214","number":20214,"commit":"484b906e5cc5a57ddbd7a730562c64f0f45438e9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/elastic-agent/builds/18182","number":18182,"commit":"7c5eb7e27e5f0fca412e110b40021226759b3e12"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-agent/builds/17705","number":17705,"commit":"24571b5e31dd8dd7c689f61c7eb3491074f8d19a"}],"number":20330}
buildkite-pr-comment-->

2025-07-09 11:07 UTC, michalpristas commented
closing in favor of https://github.com/elastic/elastic-agent/pull/8896
i picked that up and missed work done here. 
thanks anyways @kruskall for following up with agent repo as well

2025-07-09 11:07 UTC, closed without merging