[CI] Backport buildkite integration tests from main
elastic/elastic-agent pull request #6323
Opened 2024-12-13 09:28 UTC by pazone

## What does this PR do?

## Why is it important?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Disruptive User Impact

## How to test this PR locally

## Related issues

-

## Questions to ask yourself

- How are we going to support this in production?
- How are we going to measure its adoption?
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

2025-02-03 12:22 UTC, v1v commented on .buildkite/scripts/steps/integration_tests_tf.sh
> +  echo "~~~ The steps is retried, starting the ESS stack again"
Can you confirm if `buildkite-agent meta-data get` can be used for secret access?

2025-02-03 12:56 UTC, pazone commented on .buildkite/scripts/steps/integration_tests_tf.sh
> +  echo "~~~ The steps is retried, starting the ESS stack again"
The management of metadata and secrets differs from that of GH Actions. It's like a cross-step key-value storage with a job scope. You have access to what you put there. You can potentially get a secret from Vault and put it in metadata. We don't do that because it might cause a leak.

2025-02-03 13:44 UTC, v1v commented on .buildkite/scripts/steps/integration_tests_tf.sh
> +  echo "~~~ The steps is retried, starting the ESS stack again"
> You can potentially get a secret from Vault and put it in metadata.  We don't do that because it might cause a leak.

IIUC, https://github.com/elastic/elastic-agent/pull/5113 does put a secret in metadata.

2025-02-03 14:07 UTC, pazone commented on .buildkite/scripts/steps/integration_tests_tf.sh
> +  echo "~~~ The steps is retried, starting the ESS stack again"
Raised a follow-up issue

2025-02-03 18:28 UTC, kuisathaverat commented on test_infra/ess/deployment.tf
> +    instance_configuration_id = "gcp.es.datahot.n2.68x10x45"
Is there any reason to pass the instance_configuration_id? By default, the `deployment_template_id` selected will get this setting from the template override. It will stop working if the 'instance_configuration_id` disappears; that could happen on every new ms version.

2025-02-03 18:28 UTC, kuisathaverat commented on test_infra/ess/deployment.tf
> +    instance_configuration_id = "gcp.kibana.n2.68x32x45"
https://github.com/elastic/elastic-agent/pull/6323/files#r1939841825

2025-02-03 20:44 UTC, pazone commented on test_infra/ess/deployment.tf
> +    instance_configuration_id = "gcp.es.datahot.n2.68x10x45"
Thanks for noticing that. This pull request just migrates ESS cluster management from a custom go-based solution that uses [this configuration](https://github.com/elastic/elastic-agent/blob/6b9ff26acd583e055b3683b0aae2f8a0bdf337cb/pkg/testing/ess/create_deployment_csp_configuration.yaml#L2) to terraform. I can discuss the issue with the team and raise a follow-up issue.

2025-02-04 10:11 UTC, kuisathaverat commented on test_infra/ess/deployment.tf
> +    instance_configuration_id = "gcp.es.datahot.n2.68x10x45"
I'm not sure why that file is used, but fixing the instance size seems pretty wrong because you are using a template from ECH and overriding the instances used (and tested) with another type without any justification. This cannot be addressed in a follow-up.

2025-02-04 11:04 UTC, kuisathaverat requested changes
We cannot override ECH hardware templates without justification. Doing so implies cost and can cause issues in the tests and the ECH service.

2025-02-04 15:52 UTC, pazone commented on test_infra/ess/deployment.tf
> +    instance_configuration_id = "gcp.es.datahot.n2.68x10x45"
1. This is a backport from the `main` to `8.17`. That means the problem you've mentioned is located in the main branch. 
2. The initial change that was made in the main branch doesn't introduce any new changes in the stack configuration. It just migrates it as it is to terraform.
3. When we want to raise a fixing PR - first we fix it in the `main` branch and then backport the fix to other branches like the `8.17`

2025-02-04 17:56 UTC, v1v commented on test_infra/ess/deployment.tf
> +    instance_configuration_id = "gcp.es.datahot.n2.68x10x45"
Can you help me to understand what PRs are actually the ones that are backported from `main`? I can only see some changes, but I cannot find the original PRs? In other words, what's the reason `mergify` is not used for backporting the PRs from `main` to `8.17`? 

I think tracking the original PR/PRs can help with the context. Otherwise, keeping track of all the changes in this PR is hard and the original reason for those changes.

Mergify plays quite well with the backports; if this PR aggregates PRs, I feel it should be decomposed in small batches.

2025-02-04 19:18 UTC, kuisathaverat commented on test_infra/ess/deployment.tf
> +    instance_configuration_id = "gcp.es.datahot.n2.68x10x45"
>This is a backport from the main to 8.17. That means the problem you've mentioned is located in the main branch.

Spread a wrong configuration because is in main does not justify the changes, and it will force you to fix it later when you can do it now.

>The initial changes that were made in the main branch don't introduce any new changes in the stack configuration. It just migrates it as it is to terraform. (The initial PR that introduces the deployment templates https://github.com/elastic/elastic-agent/pull/3547)
When we want to raise a fixing PR - first we fix it in the main branch and then backport the fix to other branches like the 8.17

Could it be better to fix the issue in the main and make only one backport?

2025-02-05 09:23 UTC, pazone commented on test_infra/ess/deployment.tf
> +    instance_configuration_id = "gcp.es.datahot.n2.68x10x45"
@v1v Unfortunately, we couldn't backport multiple selective pull requests with mergify. You can find the list of the backported pull requests in the related issue. We discussed it previously, and this is the most effective way that we could find to backport multiple cherry-picked pull requests in terms of CI costs, speed, and reversibility

2025-02-05 09:28 UTC, v1v commented on test_infra/ess/deployment.tf
> +    instance_configuration_id = "gcp.es.datahot.n2.68x10x45"
> we couldn't backport multiple selective pull requests with mergify

It's better to backport individual PRs instead of a massive one with multiple PRs.

Otherwise, it's hard/impossible to know if a branch has all the PRs from `main`. I understand the concerns about solving conflicts, but from the git history point of view there are plenty of benefits. Git blame/log will not help to know rationale for a change in a release branch that didn't use the standard approach for using one backport per PR and target branch

2025-02-05 15:11 UTC, pazone commented on test_infra/ess/deployment.tf
> +    instance_configuration_id = "gcp.es.datahot.n2.68x10x45"
@pchila Do you happen to remember why did we use [this configuration](https://github.com/elastic/elastic-agent/blob/6b9ff26acd583e055b3683b0aae2f8a0bdf337cb/pkg/testing/ess/create_deployment_csp_configuration.yaml#L2)?

2025-02-05 15:37 UTC, pchila commented on test_infra/ess/deployment.tf
> +    instance_configuration_id = "gcp.es.datahot.n2.68x10x45"
> @pchila Do you happen to remember why did we use [this configuration](https://github.com/elastic/elastic-agent/blob/6b9ff26acd583e055b3683b0aae2f8a0bdf337cb/pkg/testing/ess/create_deployment_csp_configuration.yaml#L2)?


This was coming from the original GCP template https://github.com/elastic/elastic-agent/pull/3547/files#diff-160183c98bcf9ae79293f7555054448bf030a6066bc2c0bb5ce31458d580373fL336
which was initially used to spin up clusters in ESS QA environment for which we had to add aws and azure as we went  though the environments from QA to Staging to Prod.
I think the original json has been derived from the ESS UI by selecting the `Equivalent API request` on the `Create deployment screen` which contains the `instance_configuration_id` attribute.
![image](https://github.com/user-attachments/assets/2154f732-2e9b-434d-891f-d5a3a825bc16)

@kuisathaverat 
If this attribute is not needed to create ESS deployments we can make a quick PR on main to remove it without any problems

2025-02-05 16:29 UTC, blakerouse approved these changes

2025-02-05 17:11 UTC, kuisathaverat approved these changes

2025-02-05 17:29 UTC, kuisathaverat commented on test_infra/ess/deployment.tf
> +    instance_configuration_id = "gcp.es.datahot.n2.68x10x45"
it is not needed

2025-02-05 17:32 UTC, merged